### ISSUE TITLE
Problem with python 3.6

### ISSUE THREAD

**Issue by jorgesmok** [conda-forge/mayavi-feedstock#18]
Hi guys, I've been working with Mayavi and python 3.5 but I'd like to use python 3.6, so I did some research regarding python 3.6 support and I found this https://github.com/conda-forge/mayavi-feedstock/pull/13, which seems to have fixed python 3.6 support. I installed mayavi with no problems, however, when I import mlab I get te following: 
```
    from mayavi import mlab
  File "C:\ProgramData\Anaconda3\lib\site-packages\mayavi\mlab.py", line 27, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "C:\ProgramData\Anaconda3\lib\site-packages\mayavi\tools\camera.py", line 25, in <module>
    from .engine_manager import get_engine
  File "C:\ProgramData\Anaconda3\lib\site-packages\mayavi\tools\engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "C:\ProgramData\Anaconda3\lib\site-packages\mayavi\core\engine.py", line 27, in <module>
    from tvtk.common import is_old_pipeline
  File "C:\ProgramData\Anaconda3\lib\site-packages\tvtk\common.py", line 13, in <module>
    vtk_major_version = vtk.vtkVersion.GetVTKMajorVersion()
AttributeError: module 'vtk' has no attribute 'vtkVersion'
```
Conda info:

```
Current conda install:

               platform : win-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.14.2
       root environment : C:\ProgramData\Anaconda3  (read only)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\Users\Jorge\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\msys\1.0\home\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Jorge\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.14.2 CPython/3.6.2 Windows/10 Windows/10.0.16299
          administrator : False
```
conda list vtk:

```
# packages in environment at C:\ProgramData\Anaconda3:
#
vtk                       7.1.1                  py36_202    conda-forge
```

**Comment by larsoner** [comment]
3.6 is no longer supported so I'm closing as wontfix
