### PR TITLE
rerender to get Python 3.6 and numpy 1.13 builds

### PR DESCRIPTION
**Pull request by grlee77**
Assuming this works, it should replace PRs #10 and #12.

### CODE REVIEW

**Comment by grlee77** [comment]
I think PyQt may have to be <5 for this to work (IIRC pyface and traitsui master branches work with Qt5, but not their released versions).

The build failure on CircleCI seems unrelated to that, though:
```
+ DISPLAY=localhost:1.0
+ xvfb-run -a bash -c /feedstock_root/build_artefacts/mayavi_1497296709396/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python setup.py install --single-version-externally-managed --record record.txt
  File "<stdin>", line 1
    upload_or_check_non_existence /recipe_root conda-forge --channel=main || exit 1
    ^
IndentationError: unexpected indent
```

**Comment by grlee77** [comment]
using `Xvfb` directly rather than relying on `xvfb-run` has fixed all of the CircleCI build failures.  I am not sure what changed that was causing the prior approach not to work.

This may also help when adding OS X builds in the future because OS X seems to come with `Xvfb`, but not `xvfb-run`.  Currently the lack of VTK packages for OS X is preventing testing that here.

**Comment by jorgesmok** [comment]
Hi guys, I've been working with Mayavi and python 3.5, and today I did some research regarding python 3.6 support and I found this pull request, which seems to have fixed python 3.6 support. I installed it with no problems, however, when I import mlab I get te following:

```
    from mayavi import mlab
  File "C:\ProgramData\Anaconda3\lib\site-packages\mayavi\mlab.py", line 27, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "C:\ProgramData\Anaconda3\lib\site-packages\mayavi\tools\camera.py", line 25, in <module>
    from .engine_manager import get_engine
  File "C:\ProgramData\Anaconda3\lib\site-packages\mayavi\tools\engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "C:\ProgramData\Anaconda3\lib\site-packages\mayavi\core\engine.py", line 27, in <module>
    from tvtk.common import is_old_pipeline
  File "C:\ProgramData\Anaconda3\lib\site-packages\tvtk\common.py", line 13, in <module>
    vtk_major_version = vtk.vtkVersion.GetVTKMajorVersion()
AttributeError: module 'vtk' has no attribute 'vtkVersion'
```
I would like to help with the Mayavi project, however I'm not any specialist whatsoever, but would be glad if I could help by freeing you some time.

**Comment by grlee77** [comment]
@jorgesmok:
It seems like there is a problem with your VTK package.  Can you paste the output of `conda info` and `conda list vtk`?
I did not encounter this problem when I tried it just now (I am on 64-bit linux with Python 3.6).  (although the fact that mayavi is pinned to older VTK 7.1 rather than the current 8.0 package did cause some other things to be rolled back to earlier versions to satisfy pinning requirements).

**Comment by jorgesmok** [comment]
Conda info:
```
Current conda install:

               platform : win-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.14.2
       root environment : C:\ProgramData\Anaconda3  (read only)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\Users\Jorge\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\msys\1.0\home\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Jorge\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.14.2 CPython/3.6.2 Windows/10 Windows/10.0.16299
          administrator : False
```
conda list vtk:
```
# packages in environment at C:\ProgramData\Anaconda3:
#
vtk                       7.1.1                  py36_202    conda-forge
```
